spring.application.name=subjectallocation
# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/localBTP
spring.datasource.username=postgres
spring.datasource.password=Princy@1301
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Settings (validate = won't touch your existing tables)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=ec2

# HikariCP Connection Pool
spring.datasource.hikari.maximum-pool-size=20

# Thymeleaf Settings
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Scheduler for hold expiry cleanup
spring.task.scheduling.pool.size=5

# Server port
server.port=8080